### ISSUE TITLE
你好的使用本sh出现了问题，能否指点一下~

### ISSUE THREAD

**Issue by lvdachao** [GikkiAres/LameBuilder#1]
进入根目录：
MacBook-Pro:lame-3.100 $ ls
ACM			STYLEGUIDE		fat
API			TODO			frontend
COPYING			USAGE			include
ChangeLog		acinclude.m4		install-sh
DEFINES			aclocal.m4		lame.bat
Dll			compile			lame.spec
HACKING			config.guess		lame.spec.in
INSTALL			config.h.in		libmp3lame
INSTALL.configure	config.log		ltmain.sh
LICENSE			config.rpath		mac
LameBuilderForiOS.sh	config.sub		macosx
Makefile.MSVC		configMS.h		misc
Makefile.am		configure		missing
Makefile.am.global	configure.in		mpglib
Makefile.in		debian			testcase.mp3
Makefile.unix		depcomp			testcase.wav
README			doc			vc_solution
README.WINGTK		dshow

******************************sh运行************************************

MacBook-Pro:lame-3.100 $ ./LameBuilderForiOS.sh 
Welcome to use lame builder for iOS,version:0.0.1
If you have any problem using this build file,you can communicate with the author by email address: GikkiAres@icloud.com
Now let's starting,you should have a cup of coffee...
Compile begin... 
Building binariy for i386...
$configure_flags is : --enable-static --disable-shared --disable-frontend
$HOST is : --host=i386-apple-darwin
$CPU is : 
$CC is : xcrun -sdk iphonesimulator clang -arch i386
$CXX is : 
$CPP is : 
$AS is : 
$CFLAGS is : -arch i386 -fembed-bitcode -miphoneos-version-min=7.0
$LDFLAGS is : -arch i386 -fembed-bitcode -miphoneos-version-min=7.0
$CPPFLAGS is : 
$prefix is : /Users/lvdachao/Desktop/YYHVideo&audio/downloads/mp3_lame/lame-3.100/thin/i386
$ARCH_SELF is : x86_64-apple-darwin19.6.0
Configure command is: /Users/lvdachao/Desktop/YYHVideo&audio/downloads/mp3_lame/lame-3.100/configure --enable-static --disable-shared --disable-frontend --host=i386-apple-darwin --build=x86_64-apple-darwin19.6.0  CC=xcrun -sdk iphonesimulator clang -arch i386 CXX=xcrun -sdk iphonesimulator clang -arch i386 CPP=xcrun -sdk iphonesimulator clang -arch i386 -E  CFLAGS=-arch i386 -fembed-bitcode -miphoneos-version-min=7.0 LDFAGS=-arch i386 -fembed-bitcode -miphoneos-version-min=7.0 CPPFLAGS=-arch i386 -fembed-bitcode -miphoneos-version-min=7.0 --prefix=/Users/lvdachao/Desktop/YYHVideo&audio/downloads/mp3_lame/lame-3.100/thin/i386
checking build system type... x86_64-apple-darwin19.6.0
checking host system type... i386-apple-darwin
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... configure: error: unsafe absolute working directory name
./LameBuilderForiOS.sh: line 124: CPPFLAGS=-arch i386 -fembed-bitcode -miphoneos-version-min=7.0: command not found
make: *** No rule to make target `clean'.  Stop.
make: *** No targets specified and no makefile found.  Stop.
make: Nothing to be done for `install'.
Building binariy for i386 finish
./LameBuilderForiOS.sh: line 135: cd: /Users/lvdachao/Desktop/YYHVideo&audio/downloads/mp3_lame/lame-3.100/thin/i386/lib/: No such file or directory
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: /Users/lvdachao/Desktop/YYHVideo&audio/downloads/mp3_lame/lame-3.100/thin/i386/lib/*.a (No such file or directory)
Building binariy for x86_64...
$configure_flags is : --enable-static --disable-shared --disable-frontend
$HOST is : --host=x86_64-apple-darwin
$CPU is : 
$CC is : xcrun -sdk iphonesimulator clang -arch x86_64
$CXX is : 
$CPP is : 
$AS is : 
$CFLAGS is : -arch x86_64 -fembed-bitcode -miphoneos-version-min=7.0
$LDFLAGS is : -arch x86_64 -fembed-bitcode -miphoneos-version-min=7.0
$CPPFLAGS is : 
$prefix is : /Users/lvdachao/Desktop/YYHVideo&audio/downloads/mp3_lame/lame-3.100/thin/x86_64
$ARCH_SELF is : x86_64-apple-darwin19.6.0
Configure command is: /Users/lvdachao/Desktop/YYHVideo&audio/downloads/mp3_lame/lame-3.100/configure --enable-static --disable-shared --disable-frontend --host=x86_64-apple-darwin --build=x86_64-apple-darwin19.6.0  CC=xcrun -sdk iphonesimulator clang -arch x86_64 CXX=xcrun -sdk iphonesimulator clang -arch x86_64 CPP=xcrun -sdk iphonesimulator clang -arch x86_64 -E  CFLAGS=-arch x86_64 -fembed-bitcode -miphoneos-version-min=7.0 LDFAGS=-arch x86_64 -fembed-bitcode -miphoneos-version-min=7.0 CPPFLAGS=-arch x86_64 -fembed-bitcode -miphoneos-version-min=7.0 --prefix=/Users/lvdachao/Desktop/YYHVideo&audio/downloads/mp3_lame/lame-3.100/thin/x86_64
checking build system type... x86_64-apple-darwin19.6.0
checking host system type... x86_64-apple-darwin
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... configure: error: unsafe absolute working directory name
./LameBuilderForiOS.sh: line 124: CPPFLAGS=-arch x86_64 -fembed-bitcode -miphoneos-version-min=7.0: command not found
make: *** No rule to make target `clean'.  Stop.
make: *** No targets specified and no makefile found.  Stop.
make: Nothing to be done for `install'.
Building binariy for x86_64 finish
./LameBuilderForiOS.sh: line 135: cd: /Users/lvdachao/Desktop/YYHVideo&audio/downloads/mp3_lame/lame-3.100/thin/x86_64/lib/: No such file or directory
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: /Users/lvdachao/Desktop/YYHVideo&audio/downloads/mp3_lame/lame-3.100/thin/x86_64/lib/*.a (No such file or directory)
Building binariy for arm64...
$configure_flags is : --enable-static --disable-shared --disable-frontend
$HOST is : --host=arm-apple-darwin
$CPU is : 
$CC is : xcrun -sdk iphoneos clang -arch arm64
$CXX is : 
$CPP is : 
$AS is : 
$CFLAGS is : -arch arm64 -fembed-bitcode -miphoneos-version-min=7.0
$LDFLAGS is : -arch arm64 -fembed-bitcode -miphoneos-version-min=7.0
$CPPFLAGS is : 
$prefix is : /Users/lvdachao/Desktop/YYHVideo&audio/downloads/mp3_lame/lame-3.100/thin/arm64
$ARCH_SELF is : x86_64-apple-darwin19.6.0
Configure command is: /Users/lvdachao/Desktop/YYHVideo&audio/downloads/mp3_lame/lame-3.100/configure --enable-static --disable-shared --disable-frontend --host=arm-apple-darwin --build=x86_64-apple-darwin19.6.0  CC=xcrun -sdk iphoneos clang -arch arm64 CXX=xcrun -sdk iphoneos clang -arch arm64 CPP=xcrun -sdk iphoneos clang -arch arm64 -E  CFLAGS=-arch arm64 -fembed-bitcode -miphoneos-version-min=7.0 LDFAGS=-arch arm64 -fembed-bitcode -miphoneos-version-min=7.0 CPPFLAGS=-arch arm64 -fembed-bitcode -miphoneos-version-min=7.0 --prefix=/Users/lvdachao/Desktop/YYHVideo&audio/downloads/mp3_lame/lame-3.100/thin/arm64
checking build system type... x86_64-apple-darwin19.6.0
checking host system type... arm-apple-darwin
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... configure: error: unsafe absolute working directory name
./LameBuilderForiOS.sh: line 124: CPPFLAGS=-arch arm64 -fembed-bitcode -miphoneos-version-min=7.0: command not found
make: *** No rule to make target `clean'.  Stop.
make: *** No targets specified and no makefile found.  Stop.
make: Nothing to be done for `install'.
Building binariy for arm64 finish
./LameBuilderForiOS.sh: line 135: cd: /Users/lvdachao/Desktop/YYHVideo&audio/downloads/mp3_lame/lame-3.100/thin/arm64/lib/: No such file or directory
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: /Users/lvdachao/Desktop/YYHVideo&audio/downloads/mp3_lame/lame-3.100/thin/arm64/lib/*.a (No such file or directory)
Building binariy for armv7s...
$configure_flags is : --enable-static --disable-shared --disable-frontend
$HOST is : --host=arm-apple-darwin
$CPU is : 
$CC is : xcrun -sdk iphoneos clang -arch armv7s
$CXX is : 
$CPP is : 
$AS is : 
$CFLAGS is : -arch armv7s -fembed-bitcode -miphoneos-version-min=7.0
$LDFLAGS is : -arch armv7s -fembed-bitcode -miphoneos-version-min=7.0
$CPPFLAGS is : 
$prefix is : /Users/lvdachao/Desktop/YYHVideo&audio/downloads/mp3_lame/lame-3.100/thin/armv7s
$ARCH_SELF is : x86_64-apple-darwin19.6.0
Configure command is: /Users/lvdachao/Desktop/YYHVideo&audio/downloads/mp3_lame/lame-3.100/configure --enable-static --disable-shared --disable-frontend --host=arm-apple-darwin --build=x86_64-apple-darwin19.6.0  CC=xcrun -sdk iphoneos clang -arch armv7s CXX=xcrun -sdk iphoneos clang -arch armv7s CPP=xcrun -sdk iphoneos clang -arch armv7s -E  CFLAGS=-arch armv7s -fembed-bitcode -miphoneos-version-min=7.0 LDFAGS=-arch armv7s -fembed-bitcode -miphoneos-version-min=7.0 CPPFLAGS=-arch armv7s -fembed-bitcode -miphoneos-version-min=7.0 --prefix=/Users/lvdachao/Desktop/YYHVideo&audio/downloads/mp3_lame/lame-3.100/thin/armv7s
checking build system type... x86_64-apple-darwin19.6.0
checking host system type... arm-apple-darwin
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... configure: error: unsafe absolute working directory name
./LameBuilderForiOS.sh: line 124: CPPFLAGS=-arch armv7s -fembed-bitcode -miphoneos-version-min=7.0: command not found
make: *** No rule to make target `clean'.  Stop.
make: *** No targets specified and no makefile found.  Stop.
make: Nothing to be done for `install'.
Building binariy for armv7s finish
./LameBuilderForiOS.sh: line 135: cd: /Users/lvdachao/Desktop/YYHVideo&audio/downloads/mp3_lame/lame-3.100/thin/armv7s/lib/: No such file or directory
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: /Users/lvdachao/Desktop/YYHVideo&audio/downloads/mp3_lame/lame-3.100/thin/armv7s/lib/*.a (No such file or directory)
Compile finish.
Building fat binaries,start.
./LameBuilderForiOS.sh: line 153: cd: /Users/lvdachao/Desktop/YYHVideo&audio/downloads/mp3_lame/lame-3.100/thin/i386/lib: No such file or directory
$LIB is *.a
cmdFind is : 
 find /Users/lvdachao/Desktop/YYHVideo&audio/downloads/mp3_lame/lame-3.100/thin -name *.a
find: /Users/lvdachao/Desktop/YYHVideo&audio/downloads/mp3_lame/lame-3.100/thin: No such file or directory
result of find is : 
 
Output file is: /Users/lvdachao/Desktop/YYHVideo&audio/downloads/mp3_lame/lame-3.100/fat/lib/*.a
find: /Users/lvdachao/Desktop/YYHVideo&audio/downloads/mp3_lame/lame-3.100/thin: No such file or directory
cmdLipo is: lipo -create  -output /Users/lvdachao/Desktop/YYHVideo&audio/downloads/mp3_lame/lame-3.100/fat/lib/*.a
find: /Users/lvdachao/Desktop/YYHVideo&audio/downloads/mp3_lame/lame-3.100/thin: No such file or directory
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: no input files specified
usage: lipo <input_file> <command> [<options> ...]
  command is one of:
    -archs
    -create
    -detailed_info
    -extract <arch_type> [-extract <arch_type> ...]
    -extract_family <arch_type> [-extract_family <arch_type> ...]
    -info
    -remove <arch_type> [-remove <arch_type> ...]
    -replace <arch_type> <file_name> [-replace <arch_type> <file_name> ...]
    -thin <arch_type>
    -verify_arch <arch_type> ...
  options are one or more of:
    -arch <arch_type> <input_file>
    -hideARM64
    -output <output_file>
    -segalign <arch_type> <alignment>
cp: /Users/lvdachao/Desktop/YYHVideo&audio/downloads/mp3_lame/lame-3.100/thin/i386/include: No such file or directory
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: /Users/lvdachao/Desktop/YYHVideo&audio/downloads/mp3_lame/lame-3.100/fat/lib/*.a (No such file or directory)
Building fat binaries,finish.
Operation done.

**Comment by GikkiAres** [comment]
这个是在连续编译多个架构时,上一个架构的Makefile文件没有清除,影响了下一个架构的编译.
我已经更新了脚本,本机确认可行

**Comment by lvdachao** [comment]
感谢~
